version: "3.8"
services:
  frontend:
    build: 
      context: ./project-panel
      dockerfile: Dockerfile
    container_name: project-panel
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./project_panel_API
      dockerfile: Dockerfile
    container_name: project_panel_API
    ports:
      - '8001:8001'
    stdin_open: true
    tty: true